# Change these first
owner: jvanrhyn # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: JvanRhyn
    url: https://jvanrhyn.co.za
  - name: Mastodon
    url: https://mastodon.social
  - name: BrightRock Iris
    url: https://iris.brightrock.co.za
status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "JvanRhyn Status"
  introMessage: Upptime is a free and open-source status monitoring solution that is easy to set up and use.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
